<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AssemblyName>CrashableServer</AssemblyName>
    <RootNamespace>Peach.TestApps.CrashableServer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>
</Project>
