<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Peach.Core</AssemblyName>
    <RootNamespace>Peach.Core</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latestMajor</LangVersion>
    <NoWarn>$(NoWarn);1701;1702;SYSLIB0011</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Publishers/Can/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IronPython" Version="3.4.2" />
    <PackageReference Include="NLog" Version="4.7.15" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.1" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>
</Project>
