<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Peach.Pro.Test</AssemblyName>
    <RootNamespace>Peach.Pro.Test.Core</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latestMajor</LangVersion>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="**/.NETFramework*" />
    <Compile Remove="Agent/Http/**/*.cs" />
    <Compile Remove="Agent/HttpChannelTests.cs" />
    <EmbeddedResource Include="Resources/**/*.json" />
    <Content Include="../../Core/Scripts/**/*">
      <Link>Scripts/%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\core\Core\Peach.Core.csproj" />
    <ProjectReference Include="..\..\..\core\Test\Peach.Core.Test.csproj" />
    <ProjectReference Include="..\..\Core\Peach.Pro.csproj" />
    <ProjectReference Include="..\..\PitTester\Peach.Pro.PitTester.csproj" />
    <ProjectReference Include="..\Apps\CrashTest\CrashTest.csproj" />
    <ProjectReference Include="..\Apps\CrashableServer\CrashableServer.csproj" />
    <ProjectReference Include="..\Apps\CrashingFileConsumer\CrashingFileConsumer.csproj" />
    <ProjectReference Include="..\Apps\UseAfterFree\UseAfterFree.csproj" />
    <ProjectReference Include="..\Apps\CrashTestDummy\CrashTestDummy.csproj" />
    <ProjectReference Include="..\..\Worker\PeachWorker.csproj" />
    <ProjectReference Include="..\..\PeachAgent\PeachAgent.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="ProDotNetZip" Version="1.20.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NLog" Version="4.7.15" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="SharpPcap" Version="6.3.1" />
  </ItemGroup>

</Project>
