<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Peach.LLM</AssemblyName>
    <RootNamespace>Peach.LLM</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../core/Core/Peach.Core.csproj" />
    <ProjectReference Include="../../pro/Core/Peach.Pro.csproj" />
    <PackageReference Include="NLog" Version="4.7.15" />
  </ItemGroup>
</Project>
