<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0-windows;net10.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>PeachXmlGenerator</AssemblyName>
    <RootNamespace>PeachXmlGenerator</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latestMajor</LangVersion>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="**/.NETFramework*" />
    <Compile Remove="OS/Windows/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Core\Peach.Core.csproj" />
    <ProjectReference Include="..\Core\Peach.Pro.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
    <PackageReference Include="PacketDotNet" Version="1.4.8" />
    <PackageReference Include="SharpPcap" Version="6.3.1" />
  </ItemGroup>

</Project>
