<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>PeachAgent</AssemblyName>
    <RootNamespace>Peach.Pro</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../core/Core/Peach.Core.csproj" />
    <ProjectReference Include="../Core/Peach.Pro.csproj" />
  </ItemGroup>
</Project>
