#!/usr/bin/env python

deps = [
	'Peach.Core.dll',
	'Peach.LLM.dll',
	'Peach.Pro.dll',
	'System.Runtime.Remoting.dll',
	'System.dll',
	'System.Management.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Data.dll',
]

pkgs = [
	'NLog',
]

bld(
	name='Peach.LLM.Validations.Mutator.exe',
	features = 'cs',
	use = deps,
	use_packages = pkgs,
	paket_settings = dict(
		frameworks = ['net45'],
	),
	source = bld.path.ant_glob('**/*.cs'),
	install_644 = 'NLog.Peach.LLM.Validations.Mutator.config'
)
