#!/usr/bin/env python

deps = [
	'Peach.Core.dll',
	'Peach.Pro.dll',
	'System.dll',
	'System.Management.dll',
	'System.Xml.dll',
	'System.Core.dll',
	'System.Data.dll',
]

pkgs = [
	'NLog'
]

frameworks = [
	'net45', 
	'Net45', 
	'net40',
	'lib',
]

bld(
	name = 'Peach.LLM.Validation.Fixer.dll',
	features = 'cs paket',
	unsafe = True,
	use = deps,
	use_packages = pkgs,
	paket_settings = dict(
		frameworks = frameworks,
	),
	source = bld.path.ant_glob('**/*.cs')
)

bld.install_files('${BINDIR}/Plugins', 'Peach.LLM.Validation.Fixer.dll')
