<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>CrashTest</AssemblyName>
    <RootNamespace>Peach.TestApps.CrashTest</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>
</Project>
