# version: "3.3"

name: add-dtls-test
services:
  llm-peach-llm:
    image: pdli/llm-peach:feature--add-dtls
    volumes:
      - ./logs:/peach/logs
    networks:
      - llm-peach-net-1
    environment:
      PROTOCOL: dtls
      PORT: 20220
      HOST: tinydtls-llm
      FIXUP: 1
      MODE: llm
      PEACH_ARGS: "--duration=5:00"

  tinydtls-llm:
    image: pdli/tinydtls
    volumes:
      - ./cov:/coverage_data
    environment:
      NAME: llm
    networks:
      - llm-peach-net-1
    stop_grace_period: 120s

  llm-peach-peach:
    image: pdli/llm-peach:feature--add-dtls
    volumes:
      - ./logs:/peach/logs
    networks:
      - llm-peach-net-2
    environment:
      PROTOCOL: dtls
      PORT: 20220
      HOST: tinydtls-peach
      FIXUP: 0
      MODE: peach
      PEACH_ARGS: "--duration=5:00"

  tinydtls-peach:
    image: pdli/tinydtls
    volumes:
      - ./cov:/coverage_data
    environment:
      NAME: peach
    networks:
      - llm-peach-net-2
    stop_grace_period: 120s

  llm-peach-two-phase:
    image: pdli/llm-peach:feature--add-dtls
    volumes:
      - ./logs:/peach/logs
    networks:
      - llm-peach-net-3
    environment:
      PROTOCOL: dtls
      PORT: 20220
      HOST: tinydtls-two-phase
      FIXUP: 1
      STRATEGY: TwoPhaseRandom
      PEACH_ARGS: "--duration=5:00"

  tinydtls-two-phase:
    image: pdli/tinydtls
    volumes:
      - ./cov:/coverage_data
    environment:
      NAME: two-phase
    networks:
      - llm-peach-net-3
    stop_grace_period: 120s

networks:
  llm-peach-net-1:
    driver: bridge
  llm-peach-net-2:
    driver: bridge
  llm-peach-net-3:
    driver: bridge
