<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AssemblyName>Peach.LLM.Validations.Common</AssemblyName>
    <RootNamespace>Peach.LLM.Validations.Common</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../core/Core/Peach.Core.csproj" />
    <ProjectReference Include="../../../pro/Core/Peach.Pro.csproj" />
  </ItemGroup>
</Project>
