<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Peach.Pro.MutatorsTest</AssemblyName>
    <RootNamespace>Peach.Pro.MutatorsTest</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latestMajor</LangVersion>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="**/.NETFramework*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Core\Peach.Core.csproj" />
    <ProjectReference Include="..\Core\Peach.Pro.csproj" />
  </ItemGroup>

</Project>
