<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <AssemblyName>PeachMinset</AssemblyName>
    <RootNamespace>Peach.Core</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Core/Peach.Core.csproj" />
    <PackageReference Include="NLog" Version="4.7.15" />
  </ItemGroup>
</Project>
